server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5432/polardb_catalog
      hikari:
        #The maximum time (ms) to spend waiting to get a connection from the pool
        connection-timeout: 2000
        #The maximum number of connections HikariCP will keep in the pool
        maximum-pool-size: 5
  application:
    #The name of the application, used by the config server to filter the configuration
    name: catalog-service
  config:
  #Imports configuration data from a config server when available
    import: "optional:configserver:"
  cloud:
    config:
      #The URL of the configuration server
      uri: http://localhost:8888
      #Timeout on waiting to connect to the config server (ms)
      request-connect-timeout: 5000
      #Timeout on waiting to read configuration data from the config server (ms)
      request-read-timeout: 5000
      #Makes a failure to connect to the config server fatal
      fail-fast: false # In production, set to true
      retry:
        #Maximum number of attempts
        max-attempts: 6
        #Initial retry interval for backoff (ms)
        initial-interval: 1000
        #Maximum retry interval for backoff (ms)
        max-interval: 2000
        #Multiplier to compute the next interval
        multiplier: 1.1
polar:
  greeting: Welcome to the local book catalog!