name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        #Checks out the current Git repository (catalog-service)
        uses: actions/checkout@v3
      - name: Set up JDK
        #Installs and configures a Java runtime
        uses: actions/setup-java@v3
        #Defines which version, distribution, and cache type to use
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Code vulnerability scanning
        #Scans the codebase for vulnerabilities using grype
        uses: anchore/scan-action@v3
        #Assigns an identifier to the current step so that it can be referenced from subsequent steps
        id: scan
        with:
          #The path to the checked-out repository
          path: "${{ github.workspace }}"
          #Whether to fail the build in the event of security vulnerabilities
          fail-build: false
          #The minimum security category to be considered as an error (low, medium, high, critical)
          severity-cutoff: high
      - name: Upload vulnerability report
        #Uploads the security vulnerability report to GitHub (SARIF format)
        uses: github/codeql-action/upload-sarif@v2
        #Uploads the report even if the previous step fails
        if: success() || failure()
        with:
          #Fetches the report from the output of the previous step
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        #Ensures the Gradle wrapper is executable, solving Windows incompatibilities
        #Runs the Gradle build task, which compiles the codebase and runs unit and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build